import { IProductImage } from '@/utils/types'

export const productImages: IProductImage[][] = [
  [
    {
      id: 'gallery-shirt-1',
      url: '/images/products/shirt.png',
      name: 'Classic White',
      size: ['M', 'XL'],
      color: {
        title: 'Trắng',
        value: '#FFFFFF',
      },
      description: 'Áo thun trắng tinh khôi, dễ dàng phối với mọi trang phục.',
      stock: 120,
      priceInVND: 250000,
      priceAfterDiscount: 200000,
    },
    {
      id: 'gallery-shirt-2',
      url: '/images/products/shirt-blue.png',
      name: 'Blue Tee',
      size: ['S', 'M', 'L', 'XL', '2XL'],
      color: {
        title: 'Xanh dương',
        value: '#0000FF',
      },
      description: 'Áo thun xanh dương mạnh mẽ, phù hợp phong cách năng động.',
      stock: 80,
      priceInVND: 270000,
      priceAfterDiscount: 216000,
    },
    {
      id: 'gallery-shirt-3',
      url: '/images/products/shirt-pink.png',
      name: 'Pink Tee',
      size: ['S', 'M', 'L', 'XL', '2XL'],
      color: {
        title: 'Hồng',
        value: '#FFC0CB',
      },
      description: 'Áo thun hồng trẻ trung, tạo điểm nhấn nổi bật.',
      stock: 60,
      priceInVND: 260000,
      priceAfterDiscount: 208000,
    },
    {
      id: 'gallery-shirt-4',
      url: '/images/products/shirt-green.png',
      name: 'Green Tee',
      size: ['S', 'XL', '2XL'],
      color: {
        title: 'Xanh lá',
        value: '#008000',
      },
      description: 'Áo thun xanh lá tươi mát, thích hợp cho ngày hè.',
      stock: 45,
      priceInVND: 255000,
      priceAfterDiscount: 204000,
    },
    {
      id: 'gallery-shirt-5',
      url: '/images/products/shirt-yellow.png',
      name: 'Yellow Tee',
      size: ['S', 'M', '2XL'],
      color: {
        title: 'Vàng',
        value: '#FFFF00',
      },
      description: 'Áo thun vàng rực rỡ, mang lại cảm giác vui tươi.',
      stock: 30,
      priceInVND: 240000,
      // Không giảm giá (20% sản phẩm không có field này)
    },
  ],
  [
    {
      id: 'gallery-cup-1',
      url: '/images/products/cup.png',
      name: 'Navy Blue',
      size: ['S', 'M', 'L'],
      color: {
        title: 'Trắng',
        value: '#FFFFFF',
      },
      description: 'Ly sứ màu xanh navy sang trọng.',
      stock: 150,
      priceInVND: 120000,
      priceAfterDiscount: 96000,
    },
    {
      id: 'gallery-cup-2',
      size: ['S', 'M', 'L'],
      name: 'Pink Cup',
      url: '/images/products/cup-pink.png',
      color: {
        title: 'Hồng',
        value: '#FFC0CB',
      },
      description: 'Ly sứ màu hồng nhẹ nhàng, phù hợp làm quà tặng.',
      stock: 90,
      priceInVND: 110000,
      priceAfterDiscount: 88000,
    },
    {
      id: 'gallery-cup-3',
      url: '/images/products/cup-aqua.png',
      name: 'Aqua Cup',
      size: ['S', 'M', 'L'],
      color: {
        title: 'Xanh ngọc',
        value: '#00FFFF',
      },
      description: 'Ly sứ màu xanh ngọc tươi mát, trẻ trung.',
      stock: 70,
      priceInVND: 115000,
      priceAfterDiscount: 92000,
    },
    {
      id: 'gallery-cup-4',
      url: '/images/products/cup-yellow.png',
      name: 'Yellow Cup',
      size: ['M', 'L'],
      color: {
        title: 'Vàng',
        value: '#FFFF00',
      },
      description: 'Ly sứ màu vàng nổi bật, năng động.',
      stock: 40,
      priceInVND: 125000,
      // Không giảm giá
    },
    {
      id: 'gallery-cup-5',
      url: '/images/products/cup-orange.png',
      name: 'Orange Cup',
      size: ['M', 'L'],
      color: {
        title: 'Cam',
        value: '#FFA500',
      },
      description: 'Ly sứ màu cam trẻ trung, cá tính.',
      stock: 20,
      priceInVND: 130000,
      priceAfterDiscount: 104000,
    },
  ],
  [
    {
      id: 'gallery-hat-1',
      url: '/images/products/hat.png',
      name: 'Charcoal',
      size: ['S', 'M', 'L'],
      color: {
        title: 'Trắng',
        value: '#FFFFFF',
      },
      description: 'Nón trắng đơn giản, dễ phối đồ.',
      stock: 200,
      priceInVND: 180000,
      priceAfterDiscount: 144000,
    },
    {
      id: 'gallery-hat-2',
      url: '/images/products/hat-pink.png',
      name: 'Pink Hat',
      size: ['XL', '2XL'],
      color: {
        title: 'Hồng',
        value: '#FFC0CB',
      },
      description: 'Nón màu hồng ngọt ngào, nữ tính.',
      stock: 100,
      priceInVND: 185000,
      priceAfterDiscount: 148000,
    },
    {
      id: 'gallery-hat-3',
      url: '/images/products/hat-blue.png',
      name: 'Blue Hat',
      size: ['2XL'],
      color: {
        title: 'Xanh dương',
        value: '#0000FF',
      },
      description: 'Nón xanh dương cá tính, nổi bật.',
      stock: 50,
      priceInVND: 190000,
      priceAfterDiscount: 152000,
    },
    {
      id: 'gallery-hat-4',
      url: '/images/products/hat-green.png',
      name: 'Green Hat',
      size: ['S', 'M'],
      color: {
        title: 'Xanh lá',
        value: '#008000',
      },
      description: 'Nón xanh lá trẻ trung, năng động.',
      stock: 30,
      priceInVND: 175000,
      // Không giảm giá
    },
    {
      id: 'gallery-hat-5',
      url: '/images/products/hat-purple.png',
      name: 'Purple Hat',
      size: ['M', 'L'],
      color: {
        title: 'Tím',
        value: '#800080',
      },
      description: 'Nón màu tím cá tính, thời trang.',
      stock: 10,
      priceInVND: 200000,
      priceAfterDiscount: 160000,
    },
  ],
  [
    {
      id: 'gallery-keychain-1',
      url: '/images/products/keychain.png',
      name: 'Forest Green',
      size: ['S', 'M', 'L'],
      color: {
        title: 'Trắng',
        value: '#FFFFFF',
      },
      description: 'Móc khóa trắng đơn giản, tinh tế.',
      stock: 180,
      priceInVND: 50000,
      priceAfterDiscount: 40000,
    },
    {
      id: 'gallery-keychain-2',
      url: '/images/products/keychain-green.png',
      name: 'Green Keychain',
      size: ['S', 'M'],
      color: {
        title: 'Xanh lá',
        value: '#008000',
      },
      description: 'Móc khóa xanh lá trẻ trung, cá tính.',
      stock: 90,
      priceInVND: 55000,
      priceAfterDiscount: 44000,
    },
    {
      id: 'gallery-keychain-3',
      url: '/images/products/keychain-orange.png',
      name: 'Orange Keychain',
      size: ['M', 'L'],
      color: {
        title: 'Cam',
        value: '#FFA500',
      },
      description: 'Móc khóa màu cam nổi bật, năng động.',
      stock: 60,
      priceInVND: 60000,
      priceAfterDiscount: 48000,
    },
    {
      id: 'gallery-keychain-4',
      url: '/images/products/keychain-pink.png',
      name: 'Pink Keychain',
      size: ['L'],
      color: {
        title: 'Hồng',
        value: '#FFC0CB',
      },
      description: 'Móc khóa màu hồng dễ thương, đáng yêu.',
      stock: 30,
      priceInVND: 65000,
      // Không giảm giá
    },
    {
      id: 'gallery-keychain-5',
      url: '/images/products/keychain-purple.png',
      name: 'Purple Keychain',
      size: ['S', 'L'],
      color: {
        title: 'Tím',
        value: '#800080',
      },
      description: 'Móc khóa màu tím cá tính, thời trang.',
      stock: 15,
      priceInVND: 70000,
      priceAfterDiscount: 56000,
    },
  ],
]
