export enum EInternalEvents {
  CLICK_ON_PAGE = 'CLICK_ON_PAGE',
  SUBMIT_PRINTED_IMAGE_ELE_PROPS = 'SUBMIT_PRINTED_IMAGE_ELE_PROPS',
  SUBMIT_TEXT_ELE_PROPS = 'SUBMIT_TEXT_ELE_PROPS',
  PICK_ELEMENT = 'PICK_ELEMENT',
}
