import { TProductImage } from '@/utils/types'

export const productImages: TProductImage[][] = [
  [
    {
      id: 'gallery-shirt-1',
      url: '/images/products/shirt.png',
      name: 'Classic White',
      size: ['M', 'XL'],
      color: {
        title: 'Trắng',
        value: '#FFFFFF',
      },
      description: 'Áo thun trắng tinh khôi, dễ dàng phối với mọi trang phục.',
      stock: 120,
      priceInVND: 250000,
      priceAfterDiscount: 200000,
      category: 'shirt',
      print_x: 25,
      print_y: 20,
      print_w: 50,
      print_h: 40,
    },
    {
      id: 'gallery-shirt-2',
      url: '/images/products/shirt-blue.png',
      name: 'Blue Tee',
      size: ['S', 'M', 'L', 'XL', '2XL'],
      color: {
        title: 'Xanh dương',
        value: '#0000FF',
      },
      description: 'Áo thun xanh dương mạnh mẽ, phù hợp phong cách năng động.',
      stock: 80,
      priceInVND: 270000,
      priceAfterDiscount: 216000,
      category: 'shirt',
      print_x: 25,
      print_y: 20,
      print_w: 50,
      print_h: 40,
    },
    {
      id: 'gallery-shirt-3',
      url: '/images/products/shirt-pink.png',
      name: 'Pink Tee',
      size: ['S', 'M', 'L', 'XL', '2XL'],
      color: {
        title: 'Hồng',
        value: '#FFC0CB',
      },
      description: 'Áo thun hồng trẻ trung, tạo điểm nhấn nổi bật.',
      stock: 60,
      priceInVND: 260000,
      priceAfterDiscount: 208000,
      category: 'shirt',
      print_x: 25,
      print_y: 20,
      print_w: 50,
      print_h: 40,
    },
    {
      id: 'gallery-shirt-4',
      url: '/images/products/shirt-green.png',
      name: 'Green Tee',
      size: ['S', 'XL', '2XL'],
      color: {
        title: 'Xanh lá',
        value: '#008000',
      },
      description: 'Áo thun xanh lá tươi mát, thích hợp cho ngày hè.',
      stock: 45,
      priceInVND: 255000,
      priceAfterDiscount: 204000,
      category: 'shirt',
    },
    {
      id: 'gallery-shirt-5',
      url: '/images/products/shirt-yellow.png',
      name: 'Yellow Tee',
      size: ['S', 'M', '2XL'],
      color: {
        title: 'Vàng',
        value: '#FFFF00',
      },
      description: 'Áo thun vàng rực rỡ, mang lại cảm giác vui tươi.',
      stock: 30,
      priceInVND: 240000,
      // Không giảm giá (20% sản phẩm không có field này)
      category: 'shirt',
    },
  ],
  [
    {
      id: 'gallery-totebag-1',
      url: '/images/products/totebag-yellow.png',
      name: 'Classic Tote',
      size: ['M', 'L'],
      color: {
        title: 'Đen',
        value: '#000000',
      },
      description: 'Túi tote đen cổ điển, dễ phối đồ.',
      stock: 100,
      priceInVND: 200000,
      priceAfterDiscount: 160000,
      category: 'totebag',
      print_x: 20,
      print_y: 30,
      print_w: 60,
      print_h: 35,
    },
    {
      id: 'gallery-totebag-2',
      url: '/images/products/totebag-gray.png',
      name: 'Natural Tote',
      size: ['M', 'L'],
      color: {
        title: 'Nâu',
        value: '#8B4513',
      },
      description: 'Túi tote nâu tự nhiên, thân thiện với môi trường.',
      stock: 80,
      priceInVND: 180000,
      priceAfterDiscount: 144000,
      category: 'totebag',
    },
    {
      id: 'gallery-totebag-3',
      url: '/images/products/totebag-green.png',
      name: 'Green Tote',
      size: ['M', 'L'],
      color: {
        title: 'Xanh lá',
        value: '#008000',
      },
      description: 'Túi tote xanh lá tươi mát, dễ thương.',
      stock: 60,
      priceInVND: 220000,
      priceAfterDiscount: 176000,
      category: 'totebag',
    },
  ],
  [
    {
      id: 'gallery-cup-1',
      url: '/images/products/cup.png',
      name: 'Navy Blue',
      size: ['S', 'M', 'L'],
      color: {
        title: 'Trắng',
        value: '#FFFFFF',
      },
      description: 'Ly sứ màu xanh navy sang trọng.',
      stock: 150,
      priceInVND: 120000,
      priceAfterDiscount: 96000,
      category: 'cup',
      print_x: 30,
      print_y: 25,
      print_w: 40,
      print_h: 35,
    },
    {
      id: 'gallery-cup-2',
      size: ['S', 'M', 'L'],
      name: 'Pink Cup',
      url: '/images/products/cup-pink.png',
      color: {
        title: 'Hồng',
        value: '#FFC0CB',
      },
      description: 'Ly sứ màu hồng nhẹ nhàng, phù hợp làm quà tặng.',
      stock: 90,
      priceInVND: 110000,
      priceAfterDiscount: 88000,
      category: 'cup',
    },
    {
      id: 'gallery-cup-3',
      url: '/images/products/cup-aqua.png',
      name: 'Aqua Cup',
      size: ['S', 'M', 'L'],
      color: {
        title: 'Xanh ngọc',
        value: '#00FFFF',
      },
      description: 'Ly sứ màu xanh ngọc tươi mát, trẻ trung.',
      stock: 70,
      priceInVND: 115000,
      priceAfterDiscount: 92000,
      category: 'cup',
    },
    {
      id: 'gallery-cup-4',
      url: '/images/products/cup-yellow.png',
      name: 'Yellow Cup',
      size: ['M', 'L'],
      color: {
        title: 'Vàng',
        value: '#FFFF00',
      },
      description: 'Ly sứ màu vàng nổi bật, năng động.',
      stock: 40,
      priceInVND: 125000,
      // Không giảm giá
      category: 'cup',
    },
    {
      id: 'gallery-cup-5',
      url: '/images/products/cup-orange.png',
      name: 'Orange Cup',
      size: ['M', 'L'],
      color: {
        title: 'Cam',
        value: '#FFA500',
      },
      description: 'Ly sứ màu cam trẻ trung, cá tính.',
      stock: 20,
      priceInVND: 130000,
      priceAfterDiscount: 104000,
      category: 'cup',
    },
  ],
  [
    {
      id: 'gallery-hat-1',
      url: '/images/products/hat.png',
      name: 'Charcoal',
      size: ['S', 'M', 'L'],
      color: {
        title: 'Trắng',
        value: '#FFFFFF',
      },
      description: 'Nón trắng đơn giản, dễ phối đồ.',
      stock: 200,
      priceInVND: 180000,
      priceAfterDiscount: 144000,
      category: 'hat',
    },
    {
      id: 'gallery-hat-2',
      url: '/images/products/hat-pink.png',
      name: 'Pink Hat',
      size: ['XL', '2XL'],
      color: {
        title: 'Hồng',
        value: '#FFC0CB',
      },
      description: 'Nón màu hồng ngọt ngào, nữ tính.',
      stock: 100,
      priceInVND: 185000,
      priceAfterDiscount: 148000,
      category: 'hat',
    },
    {
      id: 'gallery-hat-3',
      url: '/images/products/hat-blue.png',
      name: 'Blue Hat',
      size: ['2XL'],
      color: {
        title: 'Xanh dương',
        value: '#0000FF',
      },
      description: 'Nón xanh dương cá tính, nổi bật.',
      stock: 50,
      priceInVND: 190000,
      priceAfterDiscount: 152000,
      category: 'hat',
    },
    {
      id: 'gallery-hat-4',
      url: '/images/products/hat-green.png',
      name: 'Green Hat',
      size: ['S', 'M'],
      color: {
        title: 'Xanh lá',
        value: '#008000',
      },
      description: 'Nón xanh lá trẻ trung, năng động.',
      stock: 30,
      priceInVND: 175000,
      // Không giảm giá
      category: 'hat',
    },
    {
      id: 'gallery-hat-5',
      url: '/images/products/hat-purple.png',
      name: 'Purple Hat',
      size: ['M', 'L'],
      color: {
        title: 'Tím',
        value: '#800080',
      },
      description: 'Nón màu tím cá tính, thời trang.',
      stock: 10,
      priceInVND: 200000,
      priceAfterDiscount: 160000,
      category: 'hat',
    },
  ],
  [
    {
      id: 'gallery-keychain-1',
      url: '/images/products/keychain.png',
      name: 'Forest Green',
      size: ['S', 'M', 'L'],
      color: {
        title: 'Trắng',
        value: '#FFFFFF',
      },
      description: 'Móc khóa trắng đơn giản, tinh tế.',
      stock: 180,
      priceInVND: 50000,
      priceAfterDiscount: 40000,
      category: 'keychain',
    },
    {
      id: 'gallery-keychain-2',
      url: '/images/products/keychain-green.png',
      name: 'Green Keychain',
      size: ['S', 'M'],
      color: {
        title: 'Xanh lá',
        value: '#008000',
      },
      description: 'Móc khóa xanh lá trẻ trung, cá tính.',
      stock: 90,
      priceInVND: 55000,
      priceAfterDiscount: 44000,
      category: 'keychain',
    },
    {
      id: 'gallery-keychain-3',
      url: '/images/products/keychain-orange.png',
      name: 'Orange Keychain',
      size: ['M', 'L'],
      color: {
        title: 'Cam',
        value: '#FFA500',
      },
      description: 'Móc khóa màu cam nổi bật, năng động.',
      stock: 60,
      priceInVND: 60000,
      priceAfterDiscount: 48000,
      category: 'keychain',
    },
    {
      id: 'gallery-keychain-4',
      url: '/images/products/keychain-pink.png',
      name: 'Pink Keychain',
      size: ['L'],
      color: {
        title: 'Hồng',
        value: '#FFC0CB',
      },
      description: 'Móc khóa màu hồng dễ thương, đáng yêu.',
      stock: 30,
      priceInVND: 65000,
      // Không giảm giá
      category: 'keychain',
    },
    {
      id: 'gallery-keychain-5',
      url: '/images/products/keychain-purple.png',
      name: 'Purple Keychain',
      size: ['S', 'L'],
      color: {
        title: 'Tím',
        value: '#800080',
      },
      description: 'Móc khóa màu tím cá tính, thời trang.',
      stock: 15,
      priceInVND: 70000,
      priceAfterDiscount: 56000,
      category: 'keychain',
    },
  ],
  [
    {
      id: 'gallery-phonecase-1',
      url: '/images/products/phonecase-black.png',
      name: 'Matte Black',
      size: ['S', 'M', 'L'],
      color: {
        title: 'Đen',
        value: '#000000',
      },
      description: 'Ốp lưng đen nhám sang trọng, chống bám vân tay.',
      stock: 140,
      priceInVND: 150000,
      priceAfterDiscount: 120000,
      category: 'phonecase',
    },
    {
      id: 'gallery-phonecase-2',
      url: '/images/products/phonecase-gray.png',
      name: 'Gray Phonecase',
      size: ['S', 'M'],
      color: {
        title: 'Xám',
        value: '#808080',
      },
      description: 'Ốp lưng xám trẻ trung, nổi bật.',
      stock: 70,
      priceInVND: 160000,
      priceAfterDiscount: 128000,
      category: 'phonecase',
    },
    {
      id: 'gallery-phonecase-3',
      url: '/images/products/phonecase-silver.png',
      name: 'Silver Phonecase',
      size: ['M', 'L'],
      color: {
        title: 'Bạc',
        value: '#C0C0C0',
      },
      description: 'Ốp lưng bạc dễ thương, nữ tính.',
      stock: 50,
      priceInVND: 155000,
      priceAfterDiscount: 124000,
      category: 'phonecase',
    },
    {
      id: 'gallery-phonecase-4',
      url: '/images/products/phonecase-orange.png',
      name: 'Orange Phonecase',
      size: ['L'],
      color: {
        title: 'Cam',
        value: '#FFA500',
      },
      description: 'Ốp lưng cam nổi bật, cá tính.',
      stock: 40,
      priceInVND: 150000,
      priceAfterDiscount: 120000,
      category: 'phonecase',
    },
    {
      id: 'gallery-phonecase-5',
      url: '/images/products/phonecase.png',
      name: 'Matte White',
      size: ['S', 'L'],
      color: {
        title: 'Trắng',
        value: '#FFFFFF',
      },
      description: 'Ốp lưng trắng tinh khôi, sang trọng.',
      stock: 20,
      priceInVND: 150000,
      priceAfterDiscount: 120000,
      category: 'phonecase',
    },
  ],

  // trending products
  [
    {
      id: 'gallery-figurine-1',
      url: '/images/products/figurine-1.png',
      name: 'Heroic Stance',
      size: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
      color: {
        title: 'Màu trong hình',
        value: 'no-specific',
      },
      description: 'Tượng nhân vật bạn bè, người thân, chi tiết tinh xảo.',
      stock: 80,
      priceInVND: 300000,
      priceAfterDiscount: 240000,
      category: 'figurine',
    },
  ],
  [
    {
      id: 'gallery-figurine-2',
      url: '/images/products/figurine-2.png',
      name: 'Dynamic Pose',
      size: ['S', 'M', 'L', 'XL', '3XL'],
      color: {
        title: 'Màu trong hình',
        value: 'no-specific',
      },
      description: 'Tượng nhân vật người yêu, sang trọng quý phái.',
      stock: 80,
      priceInVND: 300000,
      priceAfterDiscount: 240000,
      category: 'figurine',
    },
  ],
]
