import { TBaseProduct } from '@/utils/types/global'

export const products: TBaseProduct[] = [
  {
    id: parseInt('gallery-shirt-1'),
    url: '/images/products/shirt.png',
    description: 'Áo thun các loại màu sắc đa dạng.',
    isTrending: false,
    name: 'T-Shirts Collection',
    printAreaList: [
      {
        id: parseInt('shirt-print-1'),
        area: {
          print_x: 25,
          print_y: 20,
          print_w: 50,
          print_h: 40,
        },
        surfaceType: 'front',
        imageUrl: '/images/products/shirt.png',
      },
      {
        id: parseInt('shirt-print-2'),
        area: {
          print_x: 25,
          print_y: 20,
          print_w: 50,
          print_h: 40,
        },
        surfaceType: 'back',
        imageUrl: '/images/products/shirt-blue.png',
      },
    ],
    images: [
      {
        id: parseInt('gallery-shirt-1'),
        name: 'Classic White - S',
        size: 'S',
        color: {
          title: 'Trắng',
          value: '#FFFFFF',
        },
        stock: 120,
        priceAmountOneSide: 250000,
        priceAmountBothSide: 450000,
        currency: 'VND',
        category: 'shirt',
      },
      {
        id: parseInt('gallery-shirt-2'),
        name: 'Blue Tee - 2XL',
        size: '2XL',
        color: {
          title: 'Xanh dương',
          value: '#0000FF',
        },
        stock: 80,
        priceAmountOneSide: 270000,
        priceAmountBothSide: 470000,
        currency: 'VND',
        category: 'shirt',
      },
      {
        id: parseInt('gallery-shirt-3'),
        name: 'Pink Tee - S',
        size: 'S',
        color: {
          title: 'Hồng',
          value: '#FFC0CB',
        },
        currency: 'VND',
        stock: 60,
        priceAmountOneSide: 260000,
        priceAmountBothSide: 460000,
        category: 'shirt',
      },
    ],
  },
  {
    id: parseInt('gallery-totebag-1'),
    url: '/images/products/totebag-yellow.png',
    name: 'Tote Bags Collection',
    description: 'Túi tote thân thiện với môi trường.',
    isTrending: false,
    printAreaList: [
      {
        id: parseInt('totebag-print-1'),
        area: {
          print_x: 20,
          print_y: 30,
          print_w: 60,
          print_h: 35,
        },
        surfaceType: 'front',
        imageUrl: '/images/products/totebag-yellow.png',
      },
      {
        id: parseInt('totebag-print-2'),
        area: {
          print_x: 20,
          print_y: 30,
          print_w: 60,
          print_h: 35,
        },
        surfaceType: 'back',
        imageUrl: '/images/products/totebag-gray.png',
      },
    ],
    images: [
      {
        id: parseInt('gallery-totebag-1'),
        name: 'Classic Tote - M',
        size: 'M',
        color: {
          title: 'Đen',
          value: '#000000',
        },
        stock: 100,
        priceAmountOneSide: 200000,
        priceAmountBothSide: 350000,
        currency: 'VND',
        category: 'totebag',
      },
      {
        id: parseInt('gallery-totebag-2'),
        name: 'Natural Tote - M',
        size: 'M',
        color: {
          title: 'Nâu',
          value: '#8B4513',
        },
        stock: 80,
        priceAmountOneSide: 180000,
        priceAmountBothSide: 320000,
        currency: 'VND',
        category: 'totebag',
      },
      {
        id: parseInt('gallery-totebag-3'),
        name: 'Green Tote - M',
        size: 'M',
        color: {
          title: 'Xanh lá',
          value: '#008000',
        },
        stock: 60,
        priceAmountOneSide: 220000,
        priceAmountBothSide: 420000,
        currency: 'VND',
        category: 'totebag',
      },
    ],
  },
  {
    id: parseInt('gallery-cup-1'),
    url: '/images/products/cup.png',
    name: 'Cups Collection',
    description: 'Ly sứ cao cấp nhiều màu sắc.',
    isTrending: false,
    printAreaList: [
      {
        id: parseInt('cup-print-1'),
        area: {
          print_x: 30,
          print_y: 25,
          print_w: 40,
          print_h: 35,
        },
        surfaceType: 'front',
        imageUrl: '/images/products/cup.png',
      },
      {
        id: parseInt('cup-print-2'),
        area: {
          print_x: 30,
          print_y: 25,
          print_w: 40,
          print_h: 35,
        },
        surfaceType: 'back',
        imageUrl: '/images/products/cup.png',
      },
    ],
    images: [
      {
        id: parseInt('gallery-cup-1'),
        name: 'Navy Blue - S',
        size: 'S',
        color: {
          title: 'Trắng',
          value: '#FFFFFF',
        },
        stock: 150,
        priceAmountOneSide: 120000,
        priceAmountBothSide: 220000,
        currency: 'VND',
        category: 'cup',
      },
      {
        id: parseInt('gallery-cup-2'),
        name: 'Pink Cup - S',
        size: 'S',
        color: {
          title: 'Hồng',
          value: '#FFC0CB',
        },
        stock: 90,
        priceAmountOneSide: 110000,
        priceAmountBothSide: 210000,
        currency: 'VND',
        category: 'cup',
      },
      {
        id: parseInt('gallery-cup-3'),
        name: 'Aqua Cup - S',
        size: 'S',
        color: {
          title: 'Xanh ngọc',
          value: '#00FFFF',
        },
        stock: 70,
        priceAmountOneSide: 115000,
        priceAmountBothSide: 215000,
        currency: 'VND',
        category: 'cup',
      },
      {
        id: parseInt('gallery-cup-4'),
        name: 'Yellow Cup - M',
        size: 'M',
        color: {
          title: 'Vàng',
          value: '#FFFF00',
        },
        stock: 40,
        priceAmountOneSide: 125000,
        priceAmountBothSide: 225000,
        currency: 'VND',
        category: 'cup',
      },
      {
        id: parseInt('gallery-cup-5'),
        name: 'Orange Cup - M',
        size: 'M',
        color: {
          title: 'Cam',
          value: '#FFA500',
        },
        stock: 20,
        priceAmountOneSide: 130000,
        priceAmountBothSide: 230000,
        currency: 'VND',
        category: 'cup',
      },
    ],
  },
  {
    id: parseInt('gallery-hat-1'),
    url: '/images/products/hat.png',
    name: 'Hats Collection',
    description: 'Nón thời trang đa dạng kiểu dáng.',
    isTrending: false,
    printAreaList: [
      {
        id: parseInt('hat-print-1'),
        area: {
          print_x: 30,
          print_y: 35,
          print_w: 40,
          print_h: 30,
        },
        surfaceType: 'front',
        imageUrl: '/images/products/hat.png',
      },
      {
        id: parseInt('hat-print-2'),
        area: {
          print_x: 30,
          print_y: 35,
          print_w: 40,
          print_h: 30,
        },
        surfaceType: 'back',
        imageUrl: '/images/products/hat.png',
      },
    ],
    images: [
      {
        id: parseInt('gallery-hat-1'),
        name: 'Charcoal - S',
        size: 'S',
        color: {
          title: 'Trắng',
          value: '#FFFFFF',
        },
        stock: 200,
        priceAmountOneSide: 180000,
        priceAmountBothSide: 350000,
        currency: 'VND',
        category: 'hat',
      },
      {
        id: parseInt('gallery-hat-2'),
        name: 'Pink Hat - XL',
        size: 'XL',
        color: {
          title: 'Hồng',
          value: '#FFC0CB',
        },
        stock: 100,
        priceAmountOneSide: 185000,
        priceAmountBothSide: 360000,
        currency: 'VND',
        category: 'hat',
      },
      {
        id: parseInt('gallery-hat-3'),
        name: 'Blue Hat - 2XL',
        size: '2XL',
        color: {
          title: 'Xanh dương',
          value: '#0000FF',
        },
        stock: 50,
        priceAmountOneSide: 190000,
        priceAmountBothSide: 370000,
        currency: 'VND',
        category: 'hat',
      },
      {
        id: parseInt('gallery-hat-4'),
        name: 'Green Hat - S',
        size: 'S',
        color: {
          title: 'Xanh lá',
          value: '#008000',
        },
        stock: 30,
        priceAmountOneSide: 175000,
        priceAmountBothSide: 340000,
        currency: 'VND',
        category: 'hat',
      },
      {
        id: parseInt('gallery-hat-5'),
        name: 'Purple Hat - M',
        size: 'M',
        color: {
          title: 'Tím',
          value: '#800080',
        },
        stock: 10,
        priceAmountOneSide: 200000,
        priceAmountBothSide: 400000,
        currency: 'VND',
        category: 'hat',
      },
    ],
  },
  {
    id: parseInt('gallery-keychain-1'),
    url: '/images/products/keychain.png',
    name: 'Keychains Collection',
    description: 'Móc khóa xinh xắn nhiều màu.',
    isTrending: false,
    printAreaList: [
      {
        id: parseInt('keychain-print-1'),
        area: {
          print_x: 20,
          print_y: 20,
          print_w: 60,
          print_h: 60,
        },
        surfaceType: 'back',
        imageUrl: '/images/products/keychain.png',
      },
      {
        id: parseInt('keychain-print-2'),
        area: {
          print_x: 20,
          print_y: 20,
          print_w: 60,
          print_h: 60,
        },
        surfaceType: 'front',
        imageUrl: '/images/products/keychain.png',
      },
    ],
    images: [
      {
        id: parseInt('gallery-keychain-1'),
        name: 'Forest Green - S',
        size: 'S',
        color: {
          title: 'Trắng',
          value: '#FFFFFF',
        },
        stock: 180,
        priceAmountOneSide: 50000,
        priceAmountBothSide: 90000,
        currency: 'VND',
        category: 'keychain',
      },
      {
        id: parseInt('gallery-keychain-2'),
        name: 'Green Keychain - S',
        size: 'S',
        color: {
          title: 'Xanh lá',
          value: '#008000',
        },
        stock: 90,
        priceAmountOneSide: 55000,
        priceAmountBothSide: 100000,
        currency: 'VND',
        category: 'keychain',
      },
      {
        id: parseInt('gallery-keychain-3'),
        name: 'Orange Keychain - M',
        size: 'M',
        color: {
          title: 'Cam',
          value: '#FFA500',
        },
        stock: 60,
        priceAmountOneSide: 60000,
        priceAmountBothSide: 110000,
        currency: 'VND',
        category: 'keychain',
      },
      {
        id: parseInt('gallery-keychain-4'),
        name: 'Pink Keychain - L',
        size: 'L',
        color: {
          title: 'Hồng',
          value: '#FFC0CB',
        },
        stock: 30,
        priceAmountOneSide: 65000,
        priceAmountBothSide: 120000,
        currency: 'VND',
        category: 'keychain',
      },
      {
        id: parseInt('gallery-keychain-5'),
        name: 'Purple Keychain - S',
        size: 'S',
        color: {
          title: 'Tím',
          value: '#800080',
        },
        stock: 15,
        priceAmountOneSide: 70000,
        priceAmountBothSide: 130000,
        currency: 'VND',
        category: 'keychain',
      },
    ],
  },
  {
    id: parseInt('gallery-phonecase-1'),
    url: '/images/products/phonecase-black.png',
    name: 'Phone Cases Collection',
    description: 'Ốp lưng bảo vệ điện thoại cao cấp.',
    isTrending: false,
    printAreaList: [
      {
        id: parseInt('phonecase-print-1'),
        area: {
          print_x: 15,
          print_y: 20,
          print_w: 70,
          print_h: 60,
        },
        surfaceType: 'front',
        imageUrl: '/images/products/phonecase-black.png',
      },
      {
        id: parseInt('phonecase-print-2'),
        area: {
          print_x: 15,
          print_y: 20,
          print_w: 70,
          print_h: 60,
        },
        surfaceType: 'back',
        imageUrl: '/images/products/phonecase-black.png',
      },
    ],
    images: [
      {
        id: parseInt('gallery-phonecase-1'),
        name: 'Matte Black - S',
        size: 'S',
        color: {
          title: 'Đen',
          value: '#000000',
        },
        stock: 140,
        priceAmountOneSide: 150000,
        priceAmountBothSide: 290000,
        currency: 'VND',
        category: 'phonecase',
      },
      {
        id: parseInt('gallery-phonecase-2'),
        name: 'Gray Phonecase - S',
        size: 'S',
        color: {
          title: 'Xám',
          value: '#808080',
        },
        stock: 70,
        priceAmountOneSide: 160000,
        priceAmountBothSide: 310000,
        currency: 'VND',
        category: 'phonecase',
      },
      {
        id: parseInt('gallery-phonecase-3'),
        name: 'Silver Phonecase - M',
        size: 'M',
        color: {
          title: 'Bạc',
          value: '#C0C0C0',
        },
        stock: 50,
        priceAmountOneSide: 155000,
        priceAmountBothSide: 320000,
        currency: 'VND',
        category: 'phonecase',
      },
      {
        id: parseInt('gallery-phonecase-4'),
        name: 'Orange Phonecase - L',
        size: 'L',
        color: {
          title: 'Cam',
          value: '#FFA500',
        },
        stock: 40,
        priceAmountOneSide: 150000,
        priceAmountBothSide: 300000,
        currency: 'VND',
        category: 'phonecase',
      },
      {
        id: parseInt('gallery-phonecase-5'),
        name: 'Matte White - S',
        size: 'S',
        color: {
          title: 'Trắng',
          value: '#FFFFFF',
        },
        stock: 20,
        priceAmountOneSide: 150000,
        priceAmountBothSide: 290000,
        currency: 'VND',
        category: 'phonecase',
      },
    ],
  },
  {
    id: parseInt('gallery-figurine-1'),
    url: '/images/products/figurine-1.png',
    name: 'Figurines Collection',
    description: 'Tượng nhân vật in 3D độc đáo.',
    isTrending: true,
    printAreaList: [
      {
        id: parseInt('figurine-print-1'),
        area: {
          print_x: 0,
          print_y: 0,
          print_w: 100,
          print_h: 100,
        },
        surfaceType: 'back',
        imageUrl: '/images/products/figurine-1.png',
      },
      {
        id: parseInt('figurine-print-2'),
        area: {
          print_x: 0,
          print_y: 0,
          print_w: 100,
          print_h: 100,
        },
        surfaceType: 'front',
        imageUrl: '/images/products/figurine-1.png',
      },
    ],
    images: [
      {
        id: parseInt('gallery-figurine-1'),
        name: 'Heroic Stance - S',
        size: 'S',
        color: {
          title: 'Màu trong hình',
          value: 'no-specific',
        },
        stock: 80,
        priceAmountOneSide: 300000,
        priceAmountBothSide: 600000,
        currency: 'VND',
        category: 'figurine',
      },
      {
        id: parseInt('gallery-figurine-2'),
        name: 'Dynamic Pose - S',
        size: 'S',
        color: {
          title: 'Màu trong hình',
          value: 'no-specific',
        },
        stock: 80,
        priceAmountOneSide: 300000,
        priceAmountBothSide: 600000,
        currency: 'VND',
        category: 'figurine',
      },
    ],
  },
]
